name: CI/CD Pipeline for Google Cloud Run

on:
  push:
    branches:
      - develop
      - main

jobs:
  build:
    name: Build and Deploy to Google Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authenticate Docker with GCR
      run: |
        echo ${{ secrets.GCP_SA_KEY }} | docker login -u _json_key --password-stdin https://gcr.io

    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/gogo_app:$GITHUB_SHA .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/gogo_app:$GITHUB_SHA

    - name: Run Migrations
      run: |
        gcloud builds submit --config cloudmigrate.yaml

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy gogo-app \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/gogo_app:$GITHUB_SHA \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated
